---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

In this repo, I provided a Python to R translation of **30 essential Pandas methods** introduced by Avi Chawla in [The Only 30 Methods You Should Master To Become A Pandas Pro](https://towardsdatascience.com/the-only-30-methods-you-should-master-to-become-a-pandas-pro-749795084bb2) published on [TowardsDataScience](https://towardsdatascience.com/). 


The discussions of some of the methods went beyond the original, with more related methods illustrated/compared for more advanced or customized tasks (pls see specific methods highlighted in the list below). I will continue to add examples or relevant methods to enrich this site, as it now serves as a reference source for myself. 

Hope you find it helpful too. Comments and suggestions are always appreciated. :)


### Please click each method below for details    



[1. <span style="color:indianred">*read_csv()*</span>: Reading a CSV](method1-read-a-csv.html)

[2. <span style="color:indianred">*to_csv()*</span>: Storing a Dataframe into a CSV](method2-store-a-dataframe.html)

[3. <span style="color:indianred">*DataFrame()*</span>: Creating a Dataframe from a Llist](method3-create-a-dataframe-from-a-list.html)

[4. <span style="color:indianred">*DataFrame()*</span>: Creating a Dataframe from a Dictionary](method4-create-a-dataframe-from-a-dictionary.html)

[5. <span style="color:indianred">*shape*</span>: The Shape of the Dataframe](method5-the-shape-of-the-dataframe.html)

[6. <span style="color:indianred">*head()*</span>: Viewing Top N Rows](method6-viewing-top-n-rows.html)

[7. <span style="color:indianred">*dtypes*</span>: Print the Datatype of Columns](method7-print-the-datatype-of-columns.html)

[8. <span style="color:indianred">*astype() & pd.to_numeric()*</span>: Modifying the Datatype of a Column](method8-modify-the-datatype-of-a-column.html)

[9. <span style="color:indianred">*info()*</span>: Printing Descriptive Info about the Dataframe (Method1)](method9-print-descriptive-info-about-the-dataframe1.html)

[10. <span style="color:indianred">*describe()*</span>: Printing Descritive Info about the Dataframe (Method2)](method10-print-descriptive-info-about-the-dataframe2.html)

[11. <span style="color:indianred">*fillna() & replace()*</span>: Filling Missing Values](method11-filling-missing-values.html) 

[12. <span style="color:indianred">*merge & join*</span>: Joining DataFrames](method12-joining-dataframes.html)

[13. <span style="color:indianred">*sort_values()*</span>: Sorting a Dataframe](method13-sorting-a-dataframe.html)

[14. <span style="color:indianred">*groupby()*</span>: Grouping a Dataframe](method14-grouping-a-dataframe.html)

[15. <span style="color:indianred">*rename()*</span>: Renaming Columns](method15-renaming-columns.html)

[16-17. <span style="color:indianred">*assign, lambda, iloc*</span>: Adding New Columns](method16-17-adding-new-columns.html)

[18. <span style="color:indianred">*query, filter, isin*</span>: Filtering a Dataframe1: Boolean filtering](method18-filteringa-dataframe1-boolean-filtering.html)

[19. <span style="color:indianred">*filter & select_dtypes*</span>: Filtering a Dataframe2: Select columns](method19-filtering-a-dataframe2-getting-columns.html)

[20. <span style="color:indianred">*loc, map, set*</span>: Filtering a Dataframe3: Select by label](method20-filtering-a-dataframe3-select-by-label.html)

[21. <span style="color:indianred">*iloc*</span>: Filtering a Dataframe4: Select by position](method21-filtering-a-dataframe4-select-by-position.html)

[22-23. <span style="color:indianred">*unique & nunique*</span>: Finding Unique Values in a Dataframe](method22-23-finding-unique-values-in-a-dataframe.html)

[24. <span style="color:indianred">*apply*</span>: Apply a Function to a Dataframe](method24-apply-a-function-to-a-dataframe.html)

[25-26. <span style="color:indianred">*duplicated & drop_duplicates*</span>: Handling Duplicates](method25-26-handling-duplicates.html)

[27. <span style="color:indianred">*value_counts, sidetable & tabyl*</span>: Standard and customized frequency tables](method27-finding-the-distribution-of-values.html)

[28. <span style="color:indianred">*reset_index(drop, inplace)*</span>: Resetting the index of a dataframe](method28-resetting-the-index-of-a-dataframe.html)

[29. <span style="color:indianred">*crosstab()*</span>: Finding Cross-Tabulation](method29-finding-cross-tabulation.html)

[30. <span style="color:indianred">*pivot_table & melt*</span>: Pivoting DataFrames](method30-pivoting-dataframe.html)


### Bonus content 💃

The below content is not limited to pandas or tidyverse. Mainly useful stuff I learned along the way. :)

[1. <span style="color:indianred">*complete()*</span>: Expand a dataframe](bonus1-complete-all-combinations.html)

[2. <span style="color:indianred">*datetime & dateutil*</span>: Working with dates in Python](bonus2-working-with-dates-in-Python.html)


