---
title: "Method #3. Creating a DataFrame from a List"
subtitle: "Python to R Translation of 30 Essential Pandas Methods"
author: "[Mena WANG](https://www.linkedin.com/in/mena-ning-wang/)"
date: "`r format(Sys.Date(), '%B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: journal

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```


```{css, echo=FALSE}

.python{
  background-color : Azure; #color names: https://en.wikipedia.org/wiki/Web_colors
  font-weight : bold;
}

.r{
  background-color : LavenderBlush; #color names: https://en.wikipedia.org/wiki/Web_colors
  font-weight : bold;
}

```

# Introduction

Python to R translation of **30 essential Pandas methods** introduced by Avi Chawla in [The Only 30 Methods You Should Master To Become A Pandas Pro](https://towardsdatascience.com/the-only-30-methods-you-should-master-to-become-a-pandas-pro-749795084bb2) published on [TowardsDataScience](https://towardsdatascience.com/).


# Set up

```{r}
# enable python in RMarkdown
library(reticulate)

```

# Method #3. Creating a DataFrame from a List

## Python

```{python}
import pandas as pd

data = [[1,2,'A'],
        [3,4,'B']]

# columns will be named 0,1,2 etc if no column names are specified
df = pd.DataFrame(data,
                  columns = ['column1', 'column2', 'column3'])

print(df)

```

## R

```{r}

data = list(list(1,2,'A'), 
            list(3,4,'B'))

# columns will be named x1, x2, x3 etc if no column names are specified
df = data.frame(matrix(unlist(data), 
                       nrow=2))


print(df)

```


