---
title: "Method #1. Reading a CSV"
subtitle: "Python to R Translation of 30 Essneital Pandas Methods"
author: "[Mena WANG](https://www.linkedin.com/in/mena-ning-wang/)"
date: "`r format(Sys.Date(), '%B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```


```{css, echo=FALSE}

.python{
  background-color : Azure; #color names: https://en.wikipedia.org/wiki/Web_colors
  font-weight : bold;
}

.r{
  background-color : LavenderBlush; #color names: https://en.wikipedia.org/wiki/Web_colors
  font-weight : bold;
}

```

# Introduction

Python to R translation of **30 essential Pandas methods** introduced by Avi Chawla in his article [The Only 30 Methods You Should Master To Become A Pandas Pro](https://towardsdatascience.com/the-only-30-methods-you-should-master-to-become-a-pandas-pro-749795084bb2) published on [TowardsDataScience](https://towardsdatascience.com/). 

# Set up

```{r}
# enable python in RMarkdown
library(reticulate)

```

# Method #1. Reading A CSV

## Python

```{python}
import pandas as pd

df = pd.read_csv('data/iris.csv')

# verify whether the object df is a dataframe
type(df)

```

## R

```{r}

library(tidyverse)

df <- read_csv('data/iris.csv')

# verify whether the object df is a dataframe
class(df)

```


